version: "3.7"

services:
  database:
    container_name: database
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: assignmentDB
    ports:
      - '4306:3306'
    volumes:
      - ./mysql:/var/lib/mysql
      - ./docker/build/database/:/docker-entrypoint-initdb.d/
  php:
    container_name: php
    build:
      context: docker
      dockerfile: Dockerfile-php
    ports:
      - '9000:9000'
    volumes:
      - ./:/var/www/project/:cached
    depends_on:
      - database

  nginx:
    container_name: nginx
    build:
      context: docker
      dockerfile: Dockerfile-nginx
    ports:
      - '8080:80'
    volumes:
      - ./:/var/www/project/:cached
    depends_on:
      - php
      - database
    links:
      - php
